# Generated by Django 3.2.3 on 2021-07-25 04:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('correo', models.EmailField(max_length=254)),
                ('telefono', phone_field.models.PhoneField(blank=True, help_text='Numero de teléfono', max_length=31)),
                ('fecha_nacimiento', models.DateField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('creditos', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.CharField(max_length=4)),
                ('hora', models.TimeField()),
                ('duracion', models.IntegerField(blank=True, null=True)),
                ('dias', models.CharField(max_length=25)),
                ('aula', models.CharField(max_length=20)),
                ('cupos', models.SmallIntegerField(default=10)),
                ('room', models.URLField(null=True)),
                ('fecha_inicio', models.DateField(null=True)),
                ('fecha_finalizacion', models.DateField(null=True)),
                ('finalizada', models.BooleanField(default=False)),
                ('alumnos', models.ManyToManyField(blank=True, to='app_academico.Alumno')),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academico.asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='OfertaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040)], default=2021)),
                ('periodo', models.CharField(choices=[('1', 'I PERIODO'), ('2', 'II PERIODO'), ('3', 'III PERIODO')], default='1', max_length=1)),
                ('estado', models.BooleanField(default=True)),
                ('clases', models.ManyToManyField(blank=True, to='app_academico.Clase')),
            ],
        ),
        migrations.CreateModel(
            name='NotasClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parcial1', models.IntegerField(blank=True, default=0, null=True)),
                ('parcial2', models.IntegerField(blank=True, default=0, null=True)),
                ('parcial3', models.IntegerField(blank=True, default=0, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academico.alumno')),
                ('clase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_academico.clase')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('telefono', phone_field.models.PhoneField(blank=True, help_text='Numero de teléfono', max_length=31)),
                ('correo', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('1', 'Mujer'), ('2', 'Hombre'), ('3', 'Otro')], default='1', max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_contratacion', models.DateField()),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_academico.docente'),
        ),
    ]
