# Generated by Django 3.2.4 on 2021-07-31 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.TextField(default='Dirección pendiente'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alumno'),
        ),
        migrations.AddField(
            model_name='docente',
            name='direccion',
            field=models.TextField(default='Dirección pendiente'),
        ),
    ]
