# Generated by Django 3.2.3 on 2021-08-02 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='alumno'),
        ),
    ]
