# Generated by Django 3.2.3 on 2021-07-25 01:41

import datetime
from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('telefono', phone_field.models.PhoneField(blank=True, help_text='Numero de teléfono', max_length=31)),
                ('correo', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('1', 'Mujer'), ('2', 'Hombre'), ('3', 'Otro')], default='1', max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_contratacion', models.DateField(default=datetime.date(2021, 7, 24))),
            ],
        ),
        migrations.AddField(
            model_name='asignatura',
            name='creditos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OfertaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040)], default=2021)),
                ('periodo', models.CharField(choices=[('1', 'I PERIODO'), ('2', 'II PERIODO'), ('3', 'III PERIODO')], default='1', max_length=1)),
                ('estado', models.BooleanField(default=True)),
                ('clases', models.ManyToManyField(blank=True, to='app_academico.Clase')),
            ],
        ),
        migrations.AddField(
            model_name='clase',
            name='alumnos',
            field=models.ManyToManyField(blank=True, null=True, to='app_academico.Alumno'),
        ),
        migrations.AddField(
            model_name='clase',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_academico.docente'),
        ),
    ]
