# Generated by Django 3.2.3 on 2021-07-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfertaAcademica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(max_length=3)),
                ('anio', models.DateField()),
                ('estado', models.BooleanField(default=True)),
                ('clases', models.ManyToManyField(blank=True, to='app_academico.Clase')),
            ],
        ),
    ]
