# Generated by Django 3.2.3 on 2021-07-25 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0002_auto_20210724_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='alumnos',
            field=models.ManyToManyField(blank=True, to='app_academico.Alumno'),
        ),
    ]
