# Generated by Django 3.2.3 on 2021-07-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0002_ofertaacademica'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaacademica',
            name='periodo',
            field=models.CharField(choices=[('1', 'I PERIODO'), ('2', 'II PERIODO'), ('3', 'III PERIODO')], default='1', max_length=1),
        ),
    ]
