# Generated by Django 3.2.3 on 2021-07-26 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0002_alter_asignatura_nombre'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notasclase',
            options={'verbose_name_plural': 'Notas Clases'},
        ),
        migrations.AlterModelOptions(
            name='ofertaacademica',
            options={'verbose_name_plural': 'Ofertas Academicas'},
        ),
        migrations.AddField(
            model_name='alumno',
            name='facultad',
            field=models.CharField(choices=[('1', 'Ingeniería en Ciencias de la Computación'), ('2', 'Ingeniería Industrial'), ('3', 'Ingeniería Civil'), ('4', 'Medicina y Cirugía'), ('5', 'Odontología'), ('6', 'Enfermería'), ('7', 'Psicología')], default='1', max_length=1),
        ),
    ]
