# Generated by Django 3.2.3 on 2021-07-26 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0003_auto_20210726_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='creditos',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='asignatura',
            name='descripcion',
            field=models.TextField(default='Descripción pendiente'),
        ),
        migrations.AlterField(
            model_name='clase',
            name='duracion',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='clase',
            name='room',
            field=models.URLField(blank=True, null=True),
        ),
    ]
