# Generated by Django 3.2.3 on 2021-07-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0003_alter_docente_fecha_contratacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='parcial',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='parcial2',
            field=models.IntegerField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='clase',
            name='parcial3',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
