# Generated by Django 3.2.3 on 2021-07-25 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0003_alter_clase_alumnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='clase',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
