# Generated by Django 3.2.3 on 2021-07-25 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0004_auto_20210724_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clase',
            name='parcial',
            field=models.IntegerField(default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='parcial2',
            field=models.IntegerField(default=0, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='clase',
            name='parcial3',
            field=models.IntegerField(default=0, max_length=3, null=True),
        ),
    ]
