# Generated by Django 3.2.5 on 2021-07-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0004_alter_ofertaacademica_anio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ofertaacademica',
            name='anio',
            field=models.IntegerField(choices=[(2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024), (2025, 2025), (2026, 2026), (2027, 2027), (2028, 2028), (2029, 2029), (2030, 2030), (2031, 2031), (2032, 2032), (2033, 2033), (2034, 2034), (2035, 2035), (2036, 2036), (2037, 2037), (2038, 2038), (2039, 2039), (2040, 2040)], default=2021),
        ),
    ]
