# Generated by Django 3.2.4 on 2021-07-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0005_alter_ofertaacademica_anio'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='creditos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='descripcion',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
