# Generated by Django 3.2.5 on 2021-07-24 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0006_estudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='telefono',
            field=models.IntegerField(blank=True),
        ),
    ]
