# Generated by Django 3.2.3 on 2021-07-24 21:17

import datetime
from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0006_auto_20210724_1059'),
    ]

    operations = [
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('apellido', models.CharField(max_length=25)),
                ('telefono', phone_field.models.PhoneField(blank=True, help_text='Numero de teléfono', max_length=31)),
                ('correo', models.EmailField(max_length=254)),
                ('genero', models.CharField(choices=[('1', 'Mujer'), ('2', 'Hombre'), ('3', 'Otro')], default='1', max_length=1)),
                ('fecha_nacimiento', models.DateField()),
                ('fecha_contratacion', models.DateField(default=datetime.date(2021, 7, 24))),
            ],
        ),
    ]
