# Generated by Django 3.2.3 on 2021-07-24 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0007_docente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
