# Generated by Django 3.2.5 on 2021-07-24 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0008_alter_estudiantes_telefono'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Estudiantes',
            new_name='Alumnos',
        ),
    ]
