# Generated by Django 3.2.5 on 2021-07-25 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_academico', '0009_rename_estudiantes_alumnos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alumnos',
            new_name='Alumno',
        ),
    ]
